name: ChartMirage
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - liblzma=5.8.1
  - libsqlite=3.51.1
  - libzlib=1.3.1
  - openssl=3.6.0
  - pip=25.3
  - python=3.12.12
  - setuptools=80.9.0
  - tk=8.6.13
  - ucrt=10.0.26100.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - wheel=0.45.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - aiosqlite==0.21.0
      - annotated-types==0.7.0
      - anyio==4.12.0
      - attrs==25.4.0
      - banks==2.2.0
      - beautifulsoup4==4.14.3
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - clip==1.0
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - dirtyjson==1.0.8
      - distro==1.9.0
      - filelock==3.20.0
      - filetype==1.2.0
      - fonttools==4.61.0
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - ftfy==6.3.1
      - greenlet==3.3.0
      - griffe==1.15.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - llama-cloud==0.1.35
      - llama-cloud-services==0.6.54
      - llama-index==0.14.10
      - llama-index-cli==0.5.3
      - llama-index-core==0.14.10
      - llama-index-embeddings-clip==0.5.1
      - llama-index-embeddings-openai==0.5.1
      - llama-index-indices-managed-llama-cloud==0.9.4
      - llama-index-instrumentation==0.4.2
      - llama-index-llms-openai==0.6.10
      - llama-index-llms-openai-like==0.5.3
      - llama-index-readers-file==0.5.5
      - llama-index-readers-llama-parse==0.5.1
      - llama-index-workflows==2.11.5
      - llama-parse==0.6.54
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - nest-asyncio==1.6.0
      - networkx==3.6
      - nltk==3.9.2
      - numpy==2.3.5
      - openai==2.9.0
      - packaging==25.0
      - pandas==2.2.3
      - pillow==12.0.0
      - platformdirs==4.5.1
      - propcache==0.4.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.2.5
      - pypdf==6.4.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - striprtf==0.0.26
      - sympy==1.14.0
      - tenacity==9.1.2
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - torch==2.9.1+cu130
      - torchvision==0.24.1+cu130
      - tqdm==4.67.1
      - transformers==4.57.3
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.6.0
      - wcwidth==0.2.14
      - wrapt==1.17.3
      - yarl==1.22.0
prefix: D:\anaconda3\envs\ChartMirage
